version: "3.9"

services:
  app:
    image: php:${PHP_VERSION}-fpm
    container_name: blockledge-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/blockledge
    volumes:
      - ./:/var/www/blockledge
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      # symfony will read DATABASE_URL from .env or from this
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - database
      - redis
    networks:
      - blockledge-net

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: blockledge-nginx
    ports:
      - "${HOST_NGINX_PORT}:80"
    volumes:
      - ./:/var/www/blockledge
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - blockledge-net

  redis:
    image: redis:${REDIS_VERSION}
    container_name: blockledge-redis
    ports:
      - "${HOST_REDIS_PORT}:6379"
    networks:
      - blockledge-net

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: blockledge-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "${HOST_POSTGRES_PORT}:5432"
    networks:
      - blockledge-net
###< doctrine/doctrine-bundle ###

networks:
  blockledge-net:
    driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
